esphome:
  name: bureau

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

ota:
  password: ""

wifi:
  ssid: "WiFi_SSID"
  password: "WiFi_Password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bureau Fallback Hotspot"
    password: "dBIEO8pQUXXa"

captive_portal:
    
web_server:
  port: 80

mqtt:
  broker: 192.168.1.210
  username: username_mqtt
  password: password_mqtt
  client_id: bureau
