esphome:
  name: bureau

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

ota:
  password: ""

wifi:
  ssid: "wifi_ssid"
  password: "wifi_password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bureau Fallback Hotspot"
    password: "dBIEO8pQUXXa"

captive_portal:
    
web_server:
  port: 80

mqtt:
  broker: 192.168.1.210
  username: mqtt_username
  password: mqtt_password
  client_id: bureau
